const API = 'http://localhost:8088/productManage'

module.exports = {
  name: '农商系统',
  // prefix: 'fanfan',
  footerText: 'Ant Design Admin  © 2018 农商系统',
  // logo: '/logo.png',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  CORS: ['http://localhost:8088'],
  openPages: ['/login', '/register', '/'],
  apiPrefix: '/api/v1',
  API,
  api: {
    adminlogin: `${API}/adminlogin`,
    sellerLogin: `${API}/sellerlogin`,
    login: `${API}/login`,
    register: `${API}/userregister`,
    sellRegister: `${API}/sellregister`,
    upload: `${API}/imgUpload`,
    checkSeller: `${API}/checkSeller`,
    prodShelves: `${API}/prodShelves`,
    prodList: `${API}/prodList`,
    deleteProd: `${API}/deleteProd`,
    updateProd: `${API}/updateProd`,
    sellerUpdate: `${API}/sellerUpdate`,
    changepsw: `${API}/changepsw`,
    unCheckList: `${API}/unCheckList`,
    prodSearch: `${API}/prodSearch`,
    addCart: `${API}/addShopCar`,
    carList: `${API}/shoppingCarList`,
    delCart: `${API}/deleteOneFromShoppingCar`,
    payCart: `${API}/payOrder`,
  },
}
